# Generated by Django 2.2 on 2020-04-05 06:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('entry_datetime', models.DateTimeField(auto_now_add=True)),
                ('entry_image', models.ImageField(null=True, upload_to='entry/<django.db.models.fields.related.ForeignKey>')),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('exit_image', models.ImageField(null=True, upload_to='entry/<django.db.models.fields.related.ForeignKey>')),
                ('status', models.BooleanField(default=0)),
                ('fare', models.PositiveIntegerField(default=0)),
                ('entry_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entry', to='core.Station')),
                ('exit_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exit', to='core.Station')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('encoding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=0, null=True, size=1000)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
            ],
        ),
    ]
