# Generated by Django 2.2 on 2020-04-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='uid',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
