# Generated by Django 2.2 on 2020-04-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
        ),
    ]
