# Generated by Django 3.0.5 on 2020-05-04 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200405_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
